//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfConsoleClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISpalanie")]
    public interface ISpalanie {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpalanie/Koszt", ReplyAction="http://tempuri.org/ISpalanie/KosztResponse")]
        double Koszt(double cena, double odleglosc, double spalanie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpalanie/Koszt", ReplyAction="http://tempuri.org/ISpalanie/KosztResponse")]
        System.Threading.Tasks.Task<double> KosztAsync(double cena, double odleglosc, double spalanie);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISpalanieChannel : WcfConsoleClient.ServiceReference1.ISpalanie, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SpalanieClient : System.ServiceModel.ClientBase<WcfConsoleClient.ServiceReference1.ISpalanie>, WcfConsoleClient.ServiceReference1.ISpalanie {
        
        public SpalanieClient() {
        }
        
        public SpalanieClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SpalanieClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpalanieClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpalanieClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Koszt(double cena, double odleglosc, double spalanie) {
            return base.Channel.Koszt(cena, odleglosc, spalanie);
        }
        
        public System.Threading.Tasks.Task<double> KosztAsync(double cena, double odleglosc, double spalanie) {
            return base.Channel.KosztAsync(cena, odleglosc, spalanie);
        }
    }
}
